name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    branches: ['main']
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r src/* src/.* root@$HOST:/var/www/html
        env:
          KEY: ${{ secrets.KEY }}
          HOST: ${{ secrets.HOST }}
